export const categoryConstants = {
	GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
	GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
	GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
};

export const productConstants = {
	GET_PRODUCTS_BY_SLUG_REQUEST: "GET_PRODUCTS_BY_SLUG_REQUEST",
	GET_PRODUCTS_BY_SLUG_SUCCESS: "GET_PRODUCTS_BY_SLUG_SUCCESS",
	GET_PRODUCTS_BY_SLUG_FAILURE: "GET_PRODUCTS_BY_SLUG_FAILURE",
};
